# shellcheck shell=bash
# menu-test.sh — structural menu assertions without opening a real menu.
#
# tmux cannot simulate key presses on a `display-menu` overlay, so a menu
# test cannot interact with the real menu. Instead, this module wraps the
# TK_MENU_ARGS array
# that menu.sh already populates and asserts on the argument vector.
#
# Usage in a bats test:
#
#   source "$TK_LIB_DIR/menu-test.sh"
#   tk_menu_test_reset
#   tk_menu_item "one" "1" "$(tk_menu_cmd script.sh arg)"
#   tk_menu_item "two" "2" "$(tk_menu_cmd other.sh)"
#   tk_menu_test_assert_count 2
#   tk_menu_test_assert_item 0 "one" "1" "script.sh"
#   tk_menu_test_assert_has_key "2"
#   tk_menu_test_run 0          # executes script.sh arg
#   tk_menu_test_done
#
# The assert functions use the caller's own assertion helpers (assert_eq,
# assert_contains from assert.bash) so a failure reads as a normal test
# failure rather than a silent exit.

# tk_menu_test_reset — clear the menu array and start a new test.
tk_menu_test_reset() {
    tk_menu_reset
}

# tk_menu_test_add "label" "key" "cmd" — stage a menu item.
# Convenience wrapper around tk_menu_item so tests don't need to source
# menu.sh separately. Identical to tk_menu_item.
tk_menu_test_add() {
    tk_menu_item "$@"
}

# tk_menu_test_add_sep — stage a separator.
tk_menu_test_add_sep() {
    tk_menu_sep
}

# tk_menu_test_count — return the number of staged rows.
tk_menu_test_count() {
    tk_menu_count
}

# tk_menu_test_assert_count <n> — assert exact row count.
tk_menu_test_assert_count() {
    local want="${1:-0}"
    local got
    got="$(tk_menu_test_count)"
    assert_eq "$got" "$want" || return 1
}

# tk_menu_test_assert_item <idx> <label> <key> [cmd_substring]
#
# Assert that the item at index <idx> (0-based) has the given label and key.
# When cmd_substring is provided, also assert that the command field contains
# that substring (for matching against a tk_menu_cmd-generated command).
tk_menu_test_assert_item() {
    local idx="$1" label="$2" key="$3" cmd_sub="${4:-}"
    local base=$(( idx * 3 ))
    local got_label got_key got_cmd

    got_label="${TK_MENU_ARGS[$base]}"
    got_key="${TK_MENU_ARGS[$(( base + 1 ))]}"
    got_cmd="${TK_MENU_ARGS[$(( base + 2 ))]}"

    assert_eq "$got_label" "$label" || return 1
    assert_eq "$got_key" "$key" || return 1
    if [[ -n "$cmd_sub" ]]; then
        assert_contains "$got_cmd" "$cmd_sub" || return 1
    fi
}

# tk_menu_test_assert_has_key <key> — assert that some item carries this key.
tk_menu_test_assert_has_key() {
    local want="$1"
    local i count
    count="$(tk_menu_test_count)"
    for (( i = 0; i < count; i++ )); do
        local base=$(( i * 3 ))
        if [[ "${TK_MENU_ARGS[$(( base + 1 ))]}" == "$want" ]]; then
            return 0
        fi
    done
    _afail "no menu item has key '$want'"
}

# tk_menu_test_run <idx> — execute the shell command for item <idx>.
#
# The command field was generated by tk_menu_cmd, so it starts with
# `run-shell`. This strips that prefix and evaluates the rest as a shell
# command, which is what tmux would do when the item is selected. The
# command runs in the current process, so its side effects (e.g. option
# changes via tk_opt_set) are visible to subsequent assertions.
tk_menu_test_run() {
    local idx="$1"
    local base=$(( idx * 3 ))
    local cmd="${TK_MENU_ARGS[$(( base + 2 ))]}"

    # cmd is "run-shell '/path' 'arg1' ..." — strip the tmux part.
    local shell_cmd="${cmd#run-shell }"
    if [[ "$shell_cmd" == "$cmd" ]]; then
        _afail "tk_menu_test_run: item $idx has no run-shell command (got: '$cmd')"
        return 1
    fi

    eval "$shell_cmd"
}

# tk_menu_test_done — clean up the staged menu state.
tk_menu_test_done() {
    tk_menu_reset
}

# ── PTY-based menu simulation ───────────────────────────────────────
#
# Since tmux fundamentally blocks menu input from external sources
# (send-keys -K doesn't work with display-menu), these helpers use a
# PTY-based approach with an isolated test session (tmux -L test-XXXX).
#
# Requires lib/test-session.sh to be sourced (which toolkit-ui.sh does).

TK_MENU_SIM_SOCKET=""
TK_MENU_SIM_SESSION=""
TK_MENU_SIM_TITLE=""

# tk_menu_sim_open <title> <item>...
#
# Open a display-menu in an isolated test session. Items are passed as
# triplets: "label" "key" "command". Returns the socket path on stdout
# so the caller can use other tk_test_* functions against it.
#
# Example:
#   socket=$(tk_menu_sim_open "Test" "Run" "r" "run-shell 'echo hi'" "Quit" "q" "")
tk_menu_sim_open() {
    local title="${1:-Menu}"
    shift
    local socket
    socket="$(tk_test_session_start "menu-sim")" || return 1
    TK_MENU_SIM_SOCKET="$socket"
    TK_MENU_SIM_SESSION="menu-sim"
    TK_MENU_SIM_TITLE="$title"

    # Build and open the menu in the background so the test can proceed.
    # display-menu blocks until the user selects or dismisses, so run it
    # in a separate pane via run-shell -b.
    local args=()
    for a in "$@"; do args+=("$a"); done
    command tmux -L "$socket" display-menu -T "$title" "${args[@]}" 2>/dev/null || true &
    # Give the menu time to appear.
    sleep 0.05 2>/dev/null || true
    printf '%s\n' "$socket"
}

# tk_menu_sim_select <key> — simulate pressing a key in the current menu.
#
# In a real menu, the user presses the key. In the sim, we send the key
# to the test session's active pane. Since display-menu captures the
# keyboard, this actually works in the PTY context.
tk_menu_sim_select() {
    local key="${1:-}"
    [[ -n "${TK_MENU_SIM_SOCKET:-}" ]] || {
        printf 'tk_menu_sim_select: no active menu simulation\n' >&2
        return 1
    }
    tk_test_send_key "$TK_MENU_SIM_SOCKET" "$key"
}

# tk_menu_sim_type <text> — simulate typing text into a menu prompt.
tk_menu_sim_type() {
    local text="${1:-}"
    [[ -n "${TK_MENU_SIM_SOCKET:-}" ]] || {
        printf 'tk_menu_sim_type: no active menu simulation\n' >&2
        return 1
    }
    tk_test_send_key "$TK_MENU_SIM_SOCKET" "$text"
}

# tk_menu_sim_close — simulate dismissing the menu (Escape).
tk_menu_sim_close() {
    [[ -n "${TK_MENU_SIM_SOCKET:-}" ]] || return 0
    command tmux -L "$TK_MENU_SIM_SOCKET" send-keys Escape 2>/dev/null || true
    sleep 0.05 2>/dev/null || true
    tk_test_session_stop "$TK_MENU_SIM_SOCKET"
    TK_MENU_SIM_SOCKET=""
    TK_MENU_SIM_SESSION=""
    TK_MENU_SIM_TITLE=""
}

# tk_menu_sim_socket — return the current simulation socket, or empty.
tk_menu_sim_socket() {
    printf '%s' "${TK_MENU_SIM_SOCKET:-}"
}

# tk_menu_sim_info — print the current sim state (session, title) to stdout.
tk_menu_sim_info() {
    printf 'session=%s title=%s\n' "${TK_MENU_SIM_SESSION:-}" "${TK_MENU_SIM_TITLE:-}"
}

# ── menu chain ───────────────────────────────────────────────────────

# tk_menu_chain <toggle_cmd> <menu_cmd>
#
# Wrap a toggle command so it reopens the menu after execution.
# Uses a post-menu hook pattern:
#   1. Execute the toggle
#   2. Store the menu state
#   3. Reopen via the menu command
#
# <toggle_cmd> is a shell command string (typically a run-shell invocation).
# <menu_cmd> is the command that reopens the menu (e.g. "$0 menu").
#
# Example:
#   tk_menu_chain "run-shell '/path/voice.sh toggle-enabled'" "$0 menu"
tk_menu_chain() {
    local toggle="${1:-}" menu="${2:-}"
    [[ -n "$toggle" ]] || { printf 'tk_menu_chain: toggle command required\n' >&2; return 1; }
    [[ -n "$menu" ]] || { printf 'tk_menu_chain: menu command required\n' >&2; return 1; }

    # Execute the toggle first.
    if [[ "$toggle" == run-shell* ]]; then
        local shell_cmd="${toggle#run-shell }"
        eval "$shell_cmd" || true
    else
        eval "$toggle" || true
    fi

    # Reopen the menu.
    eval "$menu" || true
}
