# shellcheck shell=bash
# menu-test.sh — structural menu assertions without opening a real menu.
#
# tmux cannot simulate key presses on a `display-menu` overlay, so a menu
# test cannot interact with the real menu. Instead, this module wraps the
# TK_MENU_ARGS array
# that menu.sh already populates and asserts on the argument vector.
#
# Usage in a bats test:
#
#   source "$TK_LIB_DIR/menu-test.sh"
#   tk_menu_test_reset
#   tk_menu_item "one" "1" "$(tk_menu_cmd script.sh arg)"
#   tk_menu_item "two" "2" "$(tk_menu_cmd other.sh)"
#   tk_menu_test_assert_count 2
#   tk_menu_test_assert_item 0 "one" "1" "script.sh"
#   tk_menu_test_assert_has_key "2"
#   tk_menu_test_run 0          # executes script.sh arg
#   tk_menu_test_done
#
# The assert functions use the caller's own assertion helpers (assert_eq,
# assert_contains from assert.bash) so a failure reads as a normal test
# failure rather than a silent exit.

# tk_menu_test_reset — clear the menu array and start a new test.
tk_menu_test_reset() {
    tk_menu_reset
}

# tk_menu_test_add "label" "key" "cmd" — stage a menu item.
# Convenience wrapper around tk_menu_item so tests don't need to source
# menu.sh separately. Identical to tk_menu_item.
tk_menu_test_add() {
    tk_menu_item "$@"
}

# tk_menu_test_add_sep — stage a separator.
tk_menu_test_add_sep() {
    tk_menu_sep
}

# tk_menu_test_count — return the number of staged rows.
tk_menu_test_count() {
    tk_menu_count
}

# tk_menu_test_assert_count <n> — assert exact row count.
tk_menu_test_assert_count() {
    local want="${1:-0}"
    local got
    got="$(tk_menu_test_count)"
    assert_eq "$got" "$want" || return 1
}

# tk_menu_test_assert_item <idx> <label> <key> [cmd_substring]
#
# Assert that the item at index <idx> (0-based) has the given label and key.
# When cmd_substring is provided, also assert that the command field contains
# that substring (for matching against a tk_menu_cmd-generated command).
tk_menu_test_assert_item() {
    local idx="$1" label="$2" key="$3" cmd_sub="${4:-}"
    local base=$(( idx * 3 ))
    local got_label got_key got_cmd

    got_label="${TK_MENU_ARGS[$base]}"
    got_key="${TK_MENU_ARGS[$(( base + 1 ))]}"
    got_cmd="${TK_MENU_ARGS[$(( base + 2 ))]}"

    assert_eq "$got_label" "$label" || return 1
    assert_eq "$got_key" "$key" || return 1
    if [[ -n "$cmd_sub" ]]; then
        assert_contains "$got_cmd" "$cmd_sub" || return 1
    fi
}

# tk_menu_test_assert_has_key <key> — assert that some item carries this key.
tk_menu_test_assert_has_key() {
    local want="$1"
    local i count
    count="$(tk_menu_test_count)"
    for (( i = 0; i < count; i++ )); do
        local base=$(( i * 3 ))
        if [[ "${TK_MENU_ARGS[$(( base + 1 ))]}" == "$want" ]]; then
            return 0
        fi
    done
    _afail "no menu item has key '$want'"
}

# tk_menu_test_run <idx> — execute the shell command for item <idx>.
#
# The command field was generated by tk_menu_cmd, so it starts with
# `run-shell`. This strips that prefix and evaluates the rest as a shell
# command, which is what tmux would do when the item is selected. The
# command runs in the current process, so its side effects (e.g. option
# changes via tk_opt_set) are visible to subsequent assertions.
tk_menu_test_run() {
    local idx="$1"
    local base=$(( idx * 3 ))
    local cmd="${TK_MENU_ARGS[$(( base + 2 ))]}"

    # cmd is "run-shell '/path' 'arg1' ..." — strip the tmux part.
    local shell_cmd="${cmd#run-shell }"
    if [[ "$shell_cmd" == "$cmd" ]]; then
        _afail "tk_menu_test_run: item $idx has no run-shell command (got: '$cmd')"
        return 1
    fi

    eval "$shell_cmd"
}

# tk_menu_test_done — clean up the staged menu state.
tk_menu_test_done() {
    tk_menu_reset
}
